import catalog from '../catalog.json' with { type: 'json' };
import en from '../locales/en.json' with { type: 'json' };
import es from '../locales/es.json' with { type: 'json' };
import '../src/components/ambient-default-define.js';
import '../src/components/badge-default-define.js';
import '../src/components/badge-feedback-define.js';
import '../src/components/badge-icon-define.js';
import '../src/components/badge-notification-define.js';
import '../src/components/badge-reference-define.js';
import '../src/components/badge-variability-define.js';
import '../src/components/banner-image-define.js';
import '../src/components/button-action-define.js';
import '../src/components/button-default-define.js';
import '../src/components/button-group-define.js';
import '../src/components/button-progress-define.js';
import '../src/components/button-row-define.js';
import '../src/components/button-share-define.js';
import '../src/components/button-tpv-pad-define.js';
import '../src/components/button-videocall-define.js';
import '../src/components/carousel-default-define.js';
import '../src/components/chat-bot-define.js';
import '../src/components/chat-button-define.js';
import '../src/components/chat-container-define.js';
import '../src/components/chat-form-define.js';
import '../src/components/clip-bot-define.js';
import '../src/components/clip-box-define.js';
import '../src/components/clip-card-define.js';
import '../src/components/clip-card-data-define.js';
import '../src/components/clip-flag-define.js';
import '../src/components/clip-microillustration-define.js';
import '../src/components/component-configuration-mixin-define.js';
import '../src/components/data-visualization-bar-define.js';
import '../src/components/data-visualization-donut-define.js';
import '../src/components/data-visualization-linear-define.js';
import '../src/components/data-visualization-maps-define.js';
import '../src/components/disable-mixin-define.js';
import '../src/components/divider-default-define.js';
import '../src/components/draggable-default-define.js';
import '../src/components/expandable-accordion-define.js';
import '../src/components/expandable-multistep-define.js';
import '../src/components/expandable-multistep-index-define.js';
import '../src/components/expandable-panel-define.js';
import '../src/components/form-calendar-define.js';
import '../src/components/form-checkbox-define.js';
import '../src/components/form-container-define.js';
import '../src/components/form-date-range-define.js';
import '../src/components/form-filter-define.js';
import '../src/components/form-input-define.js';
import '../src/components/form-multiselect-define.js';
import '../src/components/form-predictive-define.js';
import '../src/components/form-radio-button-define.js';
import '../src/components/form-range-define.js';
import '../src/components/form-rating-define.js';
import '../src/components/form-scanner-define.js';
import '../src/components/form-scratch-define.js';
import '../src/components/form-select-define.js';
import '../src/components/form-select-filter-define.js';
import '../src/components/form-sign-define.js';
import '../src/components/form-toggle-define.js';
import '../src/components/form-uploader-define.js';
import '../src/components/form-verification-define.js';
import '../src/components/header-category-define.js';
import '../src/components/header-main-define.js';
import '../src/components/header-navigation-define.js';
import '../src/components/header-public-define.js';
import '../src/components/help-modal-define.js';
import '../src/components/help-onboarding-define.js';
import '../src/components/help-tooltip-define.js';
import '../src/components/list-budget-define.js';
import '../src/components/list-bullet-define.js';
import '../src/components/list-swipe-define.js';
import '../src/components/map-dynamic-define.js';
import '../src/components/map-static-define.js';
import '../src/components/navigation-menu-define.js';
import '../src/components/navigation-tab-bar-define.js';
import '../src/components/notification-contextual-define.js';
import '../src/components/notification-help-define.js';
import '../src/components/notification-message-define.js';
import '../src/components/notification-status-define.js';
import '../src/components/notification-toast-define.js';
import '../src/components/panel-audio-player-define.js';
import '../src/components/panel-code-number-define.js';
import '../src/components/panel-comparative-define.js';
import '../src/components/panel-container-define.js';
import '../src/components/panel-iframe-define.js';
import '../src/components/panel-photo-define.js';
import '../src/components/panel-risk-define.js';
import '../src/components/panel-side-define.js';
import '../src/components/progress-content-define.js';
import '../src/components/progress-step-define.js';
import '../src/components/progress-stepped-process-define.js';
import '../src/components/progress-timer-define.js';
import '../src/components/progress-vertical-step-define.js';
import '../src/components/skeleton-default-define.js';
import '../src/components/tab-default-define.js';
import '../src/components/table-body-define.js';
import '../src/components/table-default-define.js';
import '../src/components/table-filter-define.js';
import '../src/components/table-footer-define.js';
import '../src/components/table-header-define.js';
import '../src/components/table-row-group-define.js';
import '../src/components/transition-container-define.js';
import '../src/components/type-amount-define.js';
import '../src/components/type-date-define.js';
import '../src/components/type-icon-define.js';
import '../src/components/type-link-define.js';
import '../src/components/type-text-define.js';
import '../src/components/widget-configuration-mixin-define.js';
import '../src/components/widget-defaults-mixin-define.js';
document.querySelector('#grid').innerHTML = "<article class=\"card\"><div class=\"tag\">open-cells-ambient-default</div><div class=\"preview\"><open-cells-ambient-default></open-cells-ambient-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-badge-default</div><div class=\"preview\"><open-cells-badge-default></open-cells-badge-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-badge-feedback</div><div class=\"preview\"><open-cells-badge-feedback></open-cells-badge-feedback></div></article><article class=\"card\"><div class=\"tag\">open-cells-badge-icon</div><div class=\"preview\"><open-cells-badge-icon></open-cells-badge-icon></div></article><article class=\"card\"><div class=\"tag\">open-cells-badge-notification</div><div class=\"preview\"><open-cells-badge-notification></open-cells-badge-notification></div></article><article class=\"card\"><div class=\"tag\">open-cells-badge-reference</div><div class=\"preview\"><open-cells-badge-reference></open-cells-badge-reference></div></article><article class=\"card\"><div class=\"tag\">open-cells-badge-variability</div><div class=\"preview\"><open-cells-badge-variability></open-cells-badge-variability></div></article><article class=\"card\"><div class=\"tag\">open-cells-banner-image</div><div class=\"preview\"><open-cells-banner-image></open-cells-banner-image></div></article><article class=\"card\"><div class=\"tag\">open-cells-button-action</div><div class=\"preview\"><open-cells-button-action></open-cells-button-action></div></article><article class=\"card\"><div class=\"tag\">open-cells-button-default</div><div class=\"preview\"><open-cells-button-default></open-cells-button-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-button-group</div><div class=\"preview\"><open-cells-button-group></open-cells-button-group></div></article><article class=\"card\"><div class=\"tag\">open-cells-button-progress</div><div class=\"preview\"><open-cells-button-progress></open-cells-button-progress></div></article><article class=\"card\"><div class=\"tag\">open-cells-button-row</div><div class=\"preview\"><open-cells-button-row></open-cells-button-row></div></article><article class=\"card\"><div class=\"tag\">open-cells-button-share</div><div class=\"preview\"><open-cells-button-share></open-cells-button-share></div></article><article class=\"card\"><div class=\"tag\">open-cells-button-tpv-pad</div><div class=\"preview\"><open-cells-button-tpv-pad></open-cells-button-tpv-pad></div></article><article class=\"card\"><div class=\"tag\">open-cells-button-videocall</div><div class=\"preview\"><open-cells-button-videocall></open-cells-button-videocall></div></article><article class=\"card\"><div class=\"tag\">open-cells-carousel-default</div><div class=\"preview\"><open-cells-carousel-default></open-cells-carousel-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-chat-bot</div><div class=\"preview\"><open-cells-chat-bot></open-cells-chat-bot></div></article><article class=\"card\"><div class=\"tag\">open-cells-chat-button</div><div class=\"preview\"><open-cells-chat-button></open-cells-chat-button></div></article><article class=\"card\"><div class=\"tag\">open-cells-chat-container</div><div class=\"preview\"><open-cells-chat-container></open-cells-chat-container></div></article><article class=\"card\"><div class=\"tag\">open-cells-chat-form</div><div class=\"preview\"><open-cells-chat-form></open-cells-chat-form></div></article><article class=\"card\"><div class=\"tag\">open-cells-clip-bot</div><div class=\"preview\"><open-cells-clip-bot></open-cells-clip-bot></div></article><article class=\"card\"><div class=\"tag\">open-cells-clip-box</div><div class=\"preview\"><open-cells-clip-box></open-cells-clip-box></div></article><article class=\"card\"><div class=\"tag\">open-cells-clip-card</div><div class=\"preview\"><open-cells-clip-card></open-cells-clip-card></div></article><article class=\"card\"><div class=\"tag\">open-cells-clip-card-data</div><div class=\"preview\"><open-cells-clip-card-data></open-cells-clip-card-data></div></article><article class=\"card\"><div class=\"tag\">open-cells-clip-flag</div><div class=\"preview\"><open-cells-clip-flag></open-cells-clip-flag></div></article><article class=\"card\"><div class=\"tag\">open-cells-clip-microillustration</div><div class=\"preview\"><open-cells-clip-microillustration></open-cells-clip-microillustration></div></article><article class=\"card\"><div class=\"tag\">open-cells-component-configuration-mixin</div><div class=\"preview\"><open-cells-component-configuration-mixin></open-cells-component-configuration-mixin></div></article><article class=\"card\"><div class=\"tag\">open-cells-data-visualization-bar</div><div class=\"preview\"><open-cells-data-visualization-bar></open-cells-data-visualization-bar></div></article><article class=\"card\"><div class=\"tag\">open-cells-data-visualization-donut</div><div class=\"preview\"><open-cells-data-visualization-donut></open-cells-data-visualization-donut></div></article><article class=\"card\"><div class=\"tag\">open-cells-data-visualization-linear</div><div class=\"preview\"><open-cells-data-visualization-linear></open-cells-data-visualization-linear></div></article><article class=\"card\"><div class=\"tag\">open-cells-data-visualization-maps</div><div class=\"preview\"><open-cells-data-visualization-maps></open-cells-data-visualization-maps></div></article><article class=\"card\"><div class=\"tag\">open-cells-disable-mixin</div><div class=\"preview\"><open-cells-disable-mixin></open-cells-disable-mixin></div></article><article class=\"card\"><div class=\"tag\">open-cells-divider-default</div><div class=\"preview\"><open-cells-divider-default></open-cells-divider-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-draggable-default</div><div class=\"preview\"><open-cells-draggable-default></open-cells-draggable-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-expandable-accordion</div><div class=\"preview\"><open-cells-expandable-accordion></open-cells-expandable-accordion></div></article><article class=\"card\"><div class=\"tag\">open-cells-expandable-multistep</div><div class=\"preview\"><open-cells-expandable-multistep></open-cells-expandable-multistep></div></article><article class=\"card\"><div class=\"tag\">open-cells-expandable-multistep-index</div><div class=\"preview\"><open-cells-expandable-multistep-index></open-cells-expandable-multistep-index></div></article><article class=\"card\"><div class=\"tag\">open-cells-expandable-panel</div><div class=\"preview\"><open-cells-expandable-panel></open-cells-expandable-panel></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-calendar</div><div class=\"preview\"><open-cells-form-calendar></open-cells-form-calendar></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-checkbox</div><div class=\"preview\"><open-cells-form-checkbox></open-cells-form-checkbox></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-container</div><div class=\"preview\"><open-cells-form-container></open-cells-form-container></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-date-range</div><div class=\"preview\"><open-cells-form-date-range></open-cells-form-date-range></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-filter</div><div class=\"preview\"><open-cells-form-filter></open-cells-form-filter></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-input</div><div class=\"preview\"><open-cells-form-input></open-cells-form-input></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-multiselect</div><div class=\"preview\"><open-cells-form-multiselect></open-cells-form-multiselect></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-predictive</div><div class=\"preview\"><open-cells-form-predictive></open-cells-form-predictive></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-radio-button</div><div class=\"preview\"><open-cells-form-radio-button></open-cells-form-radio-button></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-range</div><div class=\"preview\"><open-cells-form-range></open-cells-form-range></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-rating</div><div class=\"preview\"><open-cells-form-rating></open-cells-form-rating></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-scanner</div><div class=\"preview\"><open-cells-form-scanner></open-cells-form-scanner></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-scratch</div><div class=\"preview\"><open-cells-form-scratch></open-cells-form-scratch></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-select</div><div class=\"preview\"><open-cells-form-select></open-cells-form-select></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-select-filter</div><div class=\"preview\"><open-cells-form-select-filter></open-cells-form-select-filter></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-sign</div><div class=\"preview\"><open-cells-form-sign></open-cells-form-sign></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-toggle</div><div class=\"preview\"><open-cells-form-toggle></open-cells-form-toggle></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-uploader</div><div class=\"preview\"><open-cells-form-uploader></open-cells-form-uploader></div></article><article class=\"card\"><div class=\"tag\">open-cells-form-verification</div><div class=\"preview\"><open-cells-form-verification></open-cells-form-verification></div></article><article class=\"card\"><div class=\"tag\">open-cells-header-category</div><div class=\"preview\"><open-cells-header-category></open-cells-header-category></div></article><article class=\"card\"><div class=\"tag\">open-cells-header-main</div><div class=\"preview\"><open-cells-header-main></open-cells-header-main></div></article><article class=\"card\"><div class=\"tag\">open-cells-header-navigation</div><div class=\"preview\"><open-cells-header-navigation></open-cells-header-navigation></div></article><article class=\"card\"><div class=\"tag\">open-cells-header-public</div><div class=\"preview\"><open-cells-header-public></open-cells-header-public></div></article><article class=\"card\"><div class=\"tag\">open-cells-help-modal</div><div class=\"preview\"><open-cells-help-modal></open-cells-help-modal></div></article><article class=\"card\"><div class=\"tag\">open-cells-help-onboarding</div><div class=\"preview\"><open-cells-help-onboarding></open-cells-help-onboarding></div></article><article class=\"card\"><div class=\"tag\">open-cells-help-tooltip</div><div class=\"preview\"><open-cells-help-tooltip></open-cells-help-tooltip></div></article><article class=\"card\"><div class=\"tag\">open-cells-list-budget</div><div class=\"preview\"><open-cells-list-budget></open-cells-list-budget></div></article><article class=\"card\"><div class=\"tag\">open-cells-list-bullet</div><div class=\"preview\"><open-cells-list-bullet></open-cells-list-bullet></div></article><article class=\"card\"><div class=\"tag\">open-cells-list-swipe</div><div class=\"preview\"><open-cells-list-swipe></open-cells-list-swipe></div></article><article class=\"card\"><div class=\"tag\">open-cells-map-dynamic</div><div class=\"preview\"><open-cells-map-dynamic></open-cells-map-dynamic></div></article><article class=\"card\"><div class=\"tag\">open-cells-map-static</div><div class=\"preview\"><open-cells-map-static></open-cells-map-static></div></article><article class=\"card\"><div class=\"tag\">open-cells-navigation-menu</div><div class=\"preview\"><open-cells-navigation-menu></open-cells-navigation-menu></div></article><article class=\"card\"><div class=\"tag\">open-cells-navigation-tab-bar</div><div class=\"preview\"><open-cells-navigation-tab-bar></open-cells-navigation-tab-bar></div></article><article class=\"card\"><div class=\"tag\">open-cells-notification-contextual</div><div class=\"preview\"><open-cells-notification-contextual></open-cells-notification-contextual></div></article><article class=\"card\"><div class=\"tag\">open-cells-notification-help</div><div class=\"preview\"><open-cells-notification-help></open-cells-notification-help></div></article><article class=\"card\"><div class=\"tag\">open-cells-notification-message</div><div class=\"preview\"><open-cells-notification-message></open-cells-notification-message></div></article><article class=\"card\"><div class=\"tag\">open-cells-notification-status</div><div class=\"preview\"><open-cells-notification-status></open-cells-notification-status></div></article><article class=\"card\"><div class=\"tag\">open-cells-notification-toast</div><div class=\"preview\"><open-cells-notification-toast></open-cells-notification-toast></div></article><article class=\"card\"><div class=\"tag\">open-cells-panel-audio-player</div><div class=\"preview\"><open-cells-panel-audio-player></open-cells-panel-audio-player></div></article><article class=\"card\"><div class=\"tag\">open-cells-panel-code-number</div><div class=\"preview\"><open-cells-panel-code-number></open-cells-panel-code-number></div></article><article class=\"card\"><div class=\"tag\">open-cells-panel-comparative</div><div class=\"preview\"><open-cells-panel-comparative></open-cells-panel-comparative></div></article><article class=\"card\"><div class=\"tag\">open-cells-panel-container</div><div class=\"preview\"><open-cells-panel-container></open-cells-panel-container></div></article><article class=\"card\"><div class=\"tag\">open-cells-panel-iframe</div><div class=\"preview\"><open-cells-panel-iframe></open-cells-panel-iframe></div></article><article class=\"card\"><div class=\"tag\">open-cells-panel-photo</div><div class=\"preview\"><open-cells-panel-photo></open-cells-panel-photo></div></article><article class=\"card\"><div class=\"tag\">open-cells-panel-risk</div><div class=\"preview\"><open-cells-panel-risk></open-cells-panel-risk></div></article><article class=\"card\"><div class=\"tag\">open-cells-panel-side</div><div class=\"preview\"><open-cells-panel-side></open-cells-panel-side></div></article><article class=\"card\"><div class=\"tag\">open-cells-progress-content</div><div class=\"preview\"><open-cells-progress-content></open-cells-progress-content></div></article><article class=\"card\"><div class=\"tag\">open-cells-progress-step</div><div class=\"preview\"><open-cells-progress-step></open-cells-progress-step></div></article><article class=\"card\"><div class=\"tag\">open-cells-progress-stepped-process</div><div class=\"preview\"><open-cells-progress-stepped-process></open-cells-progress-stepped-process></div></article><article class=\"card\"><div class=\"tag\">open-cells-progress-timer</div><div class=\"preview\"><open-cells-progress-timer></open-cells-progress-timer></div></article><article class=\"card\"><div class=\"tag\">open-cells-progress-vertical-step</div><div class=\"preview\"><open-cells-progress-vertical-step></open-cells-progress-vertical-step></div></article><article class=\"card\"><div class=\"tag\">open-cells-skeleton-default</div><div class=\"preview\"><open-cells-skeleton-default></open-cells-skeleton-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-tab-default</div><div class=\"preview\"><open-cells-tab-default></open-cells-tab-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-table-body</div><div class=\"preview\"><open-cells-table-body></open-cells-table-body></div></article><article class=\"card\"><div class=\"tag\">open-cells-table-default</div><div class=\"preview\"><open-cells-table-default></open-cells-table-default></div></article><article class=\"card\"><div class=\"tag\">open-cells-table-filter</div><div class=\"preview\"><open-cells-table-filter></open-cells-table-filter></div></article><article class=\"card\"><div class=\"tag\">open-cells-table-footer</div><div class=\"preview\"><open-cells-table-footer></open-cells-table-footer></div></article><article class=\"card\"><div class=\"tag\">open-cells-table-header</div><div class=\"preview\"><open-cells-table-header></open-cells-table-header></div></article><article class=\"card\"><div class=\"tag\">open-cells-table-row-group</div><div class=\"preview\"><open-cells-table-row-group></open-cells-table-row-group></div></article><article class=\"card\"><div class=\"tag\">open-cells-transition-container</div><div class=\"preview\"><open-cells-transition-container></open-cells-transition-container></div></article><article class=\"card\"><div class=\"tag\">open-cells-type-amount</div><div class=\"preview\"><open-cells-type-amount></open-cells-type-amount></div></article><article class=\"card\"><div class=\"tag\">open-cells-type-date</div><div class=\"preview\"><open-cells-type-date></open-cells-type-date></div></article><article class=\"card\"><div class=\"tag\">open-cells-type-icon</div><div class=\"preview\"><open-cells-type-icon></open-cells-type-icon></div></article><article class=\"card\"><div class=\"tag\">open-cells-type-link</div><div class=\"preview\"><open-cells-type-link></open-cells-type-link></div></article><article class=\"card\"><div class=\"tag\">open-cells-type-text</div><div class=\"preview\"><open-cells-type-text></open-cells-type-text></div></article><article class=\"card\"><div class=\"tag\">open-cells-widget-configuration-mixin</div><div class=\"preview\"><open-cells-widget-configuration-mixin></open-cells-widget-configuration-mixin></div></article><article class=\"card\"><div class=\"tag\">open-cells-widget-defaults-mixin</div><div class=\"preview\"><open-cells-widget-defaults-mixin></open-cells-widget-defaults-mixin></div></article>";
const localeCatalogs = { en, es };
const events = [];
const eventList = document.querySelector('#events');
const eventCount = document.querySelector('#event-count');
const eventNumber = document.querySelector('#event-number');
document.querySelector('#component-count').textContent = catalog.components.length + ' components';
const applyLocale = language => {
  document.documentElement.lang = language;
  for (const component of catalog.components) {
    const element = document.querySelector(component.tagName);
    if (element) element.locale = localeCatalogs[language][component.slug];
  }
};
const renderEvents = () => {
  eventCount.textContent = events.length + (events.length === 1 ? ' event' : ' events');
  eventNumber.textContent = String(events.length).padStart(2, '0');
  eventList.innerHTML = events.length ? events.slice(-12).reverse().map(event => '<li><strong>' + event.name + '</strong><br><code>' + JSON.stringify(event.detail) + '</code></li>').join('') : '<li class="empty">No events captured yet.</li>';
};
for (const component of catalog.components) document.addEventListener(component.eventName, event => {
  events.push({ name: event.type, detail: event.detail });
  renderEvents();
});
document.querySelector('#language').addEventListener('change', event => applyLocale(event.target.value));
applyLocale('en');
renderEvents();
